# Generated by Django 5.1.2 on 2025-05-19 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_plan_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="post",
            name="time",
        ),
        migrations.AlterField(
            model_name="day",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="days",
                to="travel_plan_app.post",
            ),
        ),
    ]
